theme: jekyll-theme-minimal
title: AEAPI
description: Asociación Española de Administradores de Propiedad Industrial
logo: assets/img/logos/vectorial.svg
baseurl: /AEAPI

github:
  is_project_page: false

exclude: ["_*"]
